
CREATE TABLE PRODUTO(
   ID INT NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   VALOR FLOAT NOT NULL,
   CONSTRAINT ITEM_PRODUTO_PK PRIMARY KEY (ID)
);


CREATE TABLE PARCELAS(
	ID SERIAL NOT NULL,
	NUM_PARC INT NOT NULL,
	VALOR FLOAT NOT NULL,
	JUROS FLOAT NOT NULL,
	PRODUTO_FK INT NOT NULL,
	CONSTRAINT PARCELAS_ID UNIQUE (ID)
);

ALTER TABLE PARCELAS ADD CONSTRAINT PARCELAS_PRODUTO_FK FOREIGN KEY (PRODUTO_FK)
REFERENCES PRODUTO (ID) 

